version: '3.2'
services:
  db:
    container_name: gabs_pgsql

    image: postgres:9.6.7

    ports:
      - 5432:5432

    volumes:
      - pgdata:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
     pgdata:
