version: '3.2'
services:
  db:
    container_name: gabs_pgsql

    image: postgres:9.6.7

    volumes:
      - /var/lib/postgresql/data

    ports:
      - 5432:5432

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
